### PR TITLE
Moved Url Mappings where is should be

### PR DESCRIPTION
**Pull request by dmahapatro**
With Grails 3 `*UrlMappings.groovy` should be under `grails-app/controllers/`.

### CODE REVIEW

**Comment by dmahapatro** [comment]
@antony Will it be possible to merge this PR and release the plugin soon?

**Comment by antony** [comment]
Hey. Done and released - sorry it took me so long, some of the Grails 3 design decisions are uttery baffling.

**Comment by dmahapatro** [comment]
No problem. :) Thank you. What would be url in bintray?

**Comment by antony** [comment]
Hi

I think I added it to the grails plugin page :)

**Comment by dmahapatro** [comment]
Thank you.

**Pull request merged**
