### PR TITLE
Grails 3 Upgrade

### PR DESCRIPTION
**Pull request by dmahapatro**
- Plugin was upgraded to Grails 3.
 - OAuth Scribe was updated to v1.3.7
 - Tests passing.
 - Sample app working.

Please merge PR.

Thanks
Dhiraj

### CODE REVIEW

**Comment by antony** [comment]
Very nice, thanks!

Will the plugin still work with Grails 2.x ?

Cheers,
Antony

**Comment by dmahapatro** [comment]
@antony Nope. This will not work with Grails 2.x. This plugin upon publish creates a `.jar` artifact as compared to `.zip` artifact with Grails 2.x.

The minimal version of Grails app should be 3.0.0 (also mentioned in the plugin descriptor)

I have had upgraded docs accordingly.

**Comment by antony** [comment]
Ok great I will merge as soon as possible

**Comment by antony** [comment]
I can't release the plugin I'm afraid. This is the case for 4 or 5 of my plugins:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenPublicationToMavenRepository'.
> Failed to publish publication 'maven' to repository 'maven'
   > java.lang.NullPointerException (no error message)
```

Not sure what to do about that error.

**Comment by dmahapatro** [comment]
@antony You can publish the plugin to bintray after creating an account. Most of the Grails plugins are published is bintray now. Reference [from audit logging plugin](https://github.com/robertoschwald/grails-audit-logging-plugin/blob/master/audit-logging/build.gradle#L74).

**Comment by antony** [comment]
Ok I didn't know that, haven't used grails for a few years now :)

Will do it asap

**Pull request merged**
